CANopen FD Master Library: QCoObject Class Reference
QCoObject Class Reference
Detailed Description
This class is the basic representation of an CANopen object, i.e. an entry inside a CANopen object dictionary.
Inherits QObject.
Public Types
enum AccessType : quint8 {
CONSTANT = 1,
READ_ONLY = 2 ,
WRITE_ONLY = 3 ,
READ_WRITE = 4
}
enum DataType : quint8 {
BOOLEAN = 1,
INTEGER8 = 2,
INTEGER16 = 3,
INTEGER32 = 4,
UNSIGNED8 = 5,
UNSIGNED16 = 6,
UNSIGNED32 = 7,
REAL32 = 8,
VISIBLE_STRING = 9,
OCTET_STRING = 10,
UNICODE_STRING = 11,
TIME_OF_DAY = 12,
TIME_DIFFERENCE = 13,
BYTE_ARRAY = 15,
REAL64 = 17,
INTEGER64 = 21,
UNSIGNED64 = 27
}
Public Member Functions
QCoObject (QObject *pclParentV=0)
QCoObject (const quint16 uwIndexV, const quint8 ubSubIndexV=0, const DataType teDataTypeV=UNSIGNED32, const AccessType teAccessTypeV=READ_WRITE, QObject *pclParentV=0)
QCoObject (const QCoObject &clOtherR)
Q_INVOKABLE enum AccessType accessType (void)
Q_INVOKABLE QString accessTypeString (void)
void attachScriptEngine (QCoScript *pclEngineV, const QString clObjectNameV="CoObject")
Q_INVOKABLE DataType dataType (void)
Q_INVOKABLE quint16 index (void) const
Q_INVOKABLE QString name (void)
Q_INVOKABLE void setIndex (const quint16 uwIndexV)
Q_INVOKABLE void setName (const QString &clNameR)
quint32 size (void)
quint32 sizeLimit (void)
Q_INVOKABLE quint8 subIndex (void)
Q_INVOKABLE QVariant value (void)
Member Enumeration Documentation
AccessType
enum QCoObject::AccessType : quint8
Access Type definitions for objects in dictionary.
Each object within the object dictionary has a specific data type.
Enumerator
CONSTANT
access type: constant
READ_ONLY
access type: read-only
WRITE_ONLY
access type: write-only
READ_WRITE
access type: read-write
DataType
enum QCoObject::DataType : quint8
Data Type definitions for objects in dictionary.
Each object within the object dictionary has a specific data type.
Enumerator
BOOLEAN
data type: boolean value
INTEGER8
data type: Signed Integer, 1 byte
INTEGER16
data type: Signed Integer, 2 bytes
INTEGER32
data type: Signed Integer, 4 bytes
UNSIGNED8
data type: Unsigned Integer, 1 byte
UNSIGNED16
data type: Unsigned Integer, 2 bytes
UNSIGNED32
data type: Unsigned Integer, 4 bytes
REAL32
The data type REAL32 is is a single precision float value of length 32. The encoding of values follows IEEE754.
VISIBLE_STRING
data type: character string
OCTET_STRING
data type: octet string
UNICODE_STRING
data type: unicode string
TIME_OF_DAY
data type: time of day value
TIME_DIFFERENCE
data type: time difference value
BYTE_ARRAY
data type: CiA 301 Domain, i.e. an array of bytes
REAL64
The data type REAL64 is a double precision float value of length 64. The encoding of values follows IEEE754.
INTEGER64
data type: Signed Integer, 8 bytes
UNSIGNED64
data type: Unsigned Integer, 8 bytes
Constructor & Destructor Documentation
QCoObject() [1/3]
QCoObject::QCoObject (QObject * pclParentV = 0)
Construct a CANopen object with an index value of 0000h and a sub-index value of 00h. The data type is set to UNSIGNED32, the access type to read-write.
Referenced by name().
QCoObject() [2/3]
QCoObject::QCoObject (const quint16 uwIndexV, const quint8 ubSubIndexV = 0, const DataType teDataTypeV = UNSIGNED32, const AccessType teAccessTypeV = READ_WRITE, QObject * pclParentV = 0)
Construct a CANopen object with an index value of uwIndexV and a sub-index value of ubSubIndexV. The data type is set to teDataTypeV, the access type to teAccessTypeV.
QCoObject() [3/3]
QCoObject::QCoObject (const QCoObject & clOtherR)
Constructs a copy of clOtherR.
Member Function Documentation
accessType()
Q_INVOKABLE enum AccessType QCoObject::accessType (void) inline
Return the access type of the object.
References accessTypeString(), and attachScriptEngine().
accessTypeString()
Q_INVOKABLE QString QCoObject::accessTypeString (void)
See also
accessType()
This method returns the object access type as a string value.
Referenced by accessType().
attachScriptEngine()
void QCoObject::attachScriptEngine (QCoScript * pclEngineV, const QString clObjectNameV = "CoObject")
Attaches a script engine to this class, the parameter clObjectNameV defines the object name inside JavaScript.
Referenced by accessType().
dataType()
Q_INVOKABLE DataType QCoObject::dataType (void) inline
See also
setDataType()
This method returns the object data type.
References index().
index()
Q_INVOKABLE quint16 QCoObject::index (void) const
Returns
Index value
See also
Referenced by dataType().
name()
Q_INVOKABLE QString QCoObject::name (void) inline
Get parameter name.
Parameters
clNameR - Reference to name object
Get the name of the object.
References QCoObject(), setIndex(), setName(), size(), sizeLimit(), subIndex(), and value().
setIndex()
Q_INVOKABLE void QCoObject::setIndex (const quint16 uwIndexV)
Parameters
uwIndex - Index of object
See also
index()
The function sets the index of the object. The allowed value range is 0000h to FFFFh
Referenced by name().
setName()
Q_INVOKABLE void QCoObject::setName (const QString & clNameR)
Parameters
clNameR - Reference to name object
Set the name of the object.
Referenced by name().
size()
quint32 QCoObject::size (void)
Get the number of data bytes of this object. The size is determined by the data type. For data types with a variable size (VISIBLE_STRING, BYTE_ARRAY, etc) the function returns the actual number of bytes stored in this object.
Referenced by name().
sizeLimit()
quint32 QCoObject::sizeLimit (void)
Return the maximum number of data bytes that can be stored in this object. The value is determined by the data type. For basic data types (INTEGER8, INTEGER16, etc) the function returns the size of the data type (i.e. 1 for INTEGER8). For data types with a variable size the function returns a limit value. Use setSizeLimit() to configure the value individually.
Referenced by name().
subIndex()
Q_INVOKABLE quint8 QCoObject::subIndex (void)
Get sub-index of dictionary object.
Returns
Sub-Index value
Referenced by name().
value()
Q_INVOKABLE QVariant QCoObject::value (void)
Get data from dictionary object.
Parameters
ubValueR - Reference to Unsigned 8-Bit value
ubTypeV - Value type definition
Returns
0 if no data available, negative values indicate an error positive values indicate number of bytes read
Referenced by name().