CANopen FD Master Library: QCoScript Class Reference
QCoScript Class Reference
Detailed Description
This class provides a generic script engine for the CANopen Master protocol stack. The class provides several built-in commands which are disabled by default. The built-in commands are enabled by the enableCommand() function.
Inherits QObject.
Public Types
enum Command_e {
eCOMMAND_ALL = 1,
eCOMMAND_DELAY,
eCOMMAND_HELP ,
eCOMMAND_RUN,
eCOMMAND_VERSION
}
Public Slots
void executeCommand (const QString clScriptCommandV)
Public Member Functions
QScriptEngine * engine (void)
void enableCommand (enum Command_e teCommandV)
Member Enumeration Documentation
Command_e
enum QCoScript::Command_e
Enumeration of all support built-in commands. The method enableCommand() allows to enable specific commands or all supported commands.
Enumerator
eCOMMAND_ALL
Enable all built-in commands
eCOMMAND_DELAY
Enable command delay()
eCOMMAND_HELP
Enable command help()
eCOMMAND_RUN
Enable command run()
eCOMMAND_VERSION
Enable command version()
Member Function Documentation
enableCommand()
void QCoScript::enableCommand (enum Command_e teCommandV)
teCommandV - Command identifier
This method enables a built-in command defined by the parameter teCommandV. All built-in commands are enabled by the value eCOMMAND_ALL.
Referenced by engine().
engine()
QScriptEngine* QCoScript::engine (void) inline
Returns
Pointer to active script engine
This method returns a pointer to the active script engine. It add be used to add the engine to scriptable classes via the addScriptEngine() method.
References enableCommand(), and executeCommand().
executeCommand
void QCoScript::executeCommand (const QString clScriptCommandV) slot
Parameters
clScriptCommandV - JavaScript command line
This method executes a JavaScript command line.
Referenced by engine().